### ISSUE TITLE
quality levels doesn't work on edge

### ISSUE THREAD

**Issue by ahmadawada11** [videojs/videojs-contrib-quality-levels#22] opened 2017-08-30 13:16 UTC
Hi,

i am using this plugin with videojs-contrib-hls and videojs-hls-source-selector it is working fine on chrome and firefox but it is not working on edge and chrome on mobile this plugin doesn't return any data. i am using videojs 6.2.6 

thank you

**Comment by mjneil** [comment] 2017-08-30 14:42
Are you using the `overrideNative` option? https://github.com/videojs/videojs-contrib-hls#overridenative

Edge and chrome mobile both support HLS playback natively. Using `overrideNative` will ensure videojs-contrib-hls will be used.

**Comment by ahmadawada11** [comment] 2017-08-31 07:46
Thanks for your fast response.
i wasn't using the overrideNative option.

Now I added the following before player declaration.
```
 videojs.options.hls.overrideNative = true;
 videojs.options.html5.nativeAudioTracks = false;
 videojs.options.html5.nativeVideoTracks = false;  
```
but it is still not working

**Comment by mjneil** [comment] 2017-08-31 15:11
Closing duplicate of https://github.com/videojs/videojs-contrib-hls/issues/1248

**Closed as completed by mjneil** 2017-08-31 15:11 UTC
